export default {
  SIGN_UP: "SIGN_UP",
  SIGN_IN: "SIGN_UP",
  LOG_OUT: "LOG_OUT",
  GET_BLOGS: "GET_BLOGS",
  GET_ANY_USER: "GET_ANY_USER",
  POST_NEW_BLOG: "POST_NEW_BLOG",
  GET_BLOG_TO_EDIT: "GET_BLOG_TO_EDIT",
  FOLLOW_ANY_USER: "FOLLOW_ANY_USER",
  DELETE_BLOG: "DELETE_BLOG",
};
